### ISSUE TITLE
Rating Reviews Page User Experience

### ISSUE THREAD

**Issue by cheseremtitus24** [Cank256/paywifigo-rating#1]
The Reviews (star rating page) should have the star rating larger and more outstanding ( so that it is not missed when filling out).
Setup the rating page responsive and fill a considerable amount of UI (current display is very small and people with old age will strain to read the prompts). Use appropriate font size and add a theme that co-insides with the WiFiGo Logo (hint of dark brown and golden shades).

**Comment by BuomYian** [comment]
**Improved the Reviews (Star Rating) page for better user experience:**
**Increased Star Rating Size and Visibility:** Made the star rating icons larger and more prominent to avoid users missing them while filling out the review.
Responsive Design: Implemented responsive design to ensure the page adapts seamlessly across different screen sizes.
**Enhanced UI with Readability:** Increased font size for prompts and overall UI elements to improve readability, especially for users with accessibility needs.
**Themed Design:** Applied a theme that aligns with the WiFiGo logo, incorporating dark brown and golden shades for a cohesive brand experience.

<img width="959" alt="Capture" src="https://github.com/Cank256/paywifigo-rating/assets/99048675/4c569710-a252-4564-bdb9-a356a211b75c">
